site_name: BMSV 1
site_description: Skriptum by Iryna Seifried und Fitzgerald Rodas

nav:
  - Startseite: index.md
  - Elektrotechnik:
      - Elektrische Größen: elektrische-groessen.md
      - Elektrische Widerstände: elektrische-widerstaende.md
      - Gleichstromwiderstandsnetze: gleichstromwiderstandsnetze.md
      - Gleichstromschaltungen: gleichstromschaltungen.md
      - Formaler Lösungsweg: formaler-loesungsweg.md
      - Energie und Leistung: energie-und-leistung.md
  - Messtechnik:
      - Messverfahren: messverfahren.md
      - Überlagerungsprinzip: ueberlagerungsprinzip.md
  - Biomedizin:
      - Biosignale: biosignale.md
      - Biomedizinische Sensortechnik: sensoren.md
  - Übungen & Tests:
      - 1. Test: test-1.md
      - Quellen: quellen.md

theme:
  name: material
  favicon: images/favicon.ico
  logo: images/Skriptum_Logo.png
  language: de
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: Dunkelmodus

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list

extra_css:
  - stylesheets/logo.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
