site_name: BMSV 1
site_description: Skriptum by Iryna Seifried und Fitzgerald Rodas

nav:
  - Startseite: index.md
  - SI-Einheiten:
      - Einleitung: si-einheiten/einleitung.md
      - SI-Basiseinheiten: si-einheiten/basiseinheiten.md
      - Abgeleitete Einheiten: si-einheiten/abgeleitete-einheiten.md
      - SI-Vorsilben: si-einheiten/vorsilben.md
      - Wissenschaftliche Notation: si-einheiten/wissenschaftliche-notation.md
      - Übungsaufgabe: si-einheiten/aufgabe1.md
      - Anwendungen: si-einheiten/anwendungen.md
      - Schreibweise: si-einheiten/schreibweise.md
      - Beispiel: si-einheiten/biosignal-beispiel.md
      - Praktische Beispiele: si-einheiten/aufgabe2.md
  - Digitaltechnik:
      - Zahlensysteme: digitaltechnik/zahlensysteme.md
      - Logik & Wahrheitstabellen: digitaltechnik/logik.md
  - Biosignale:
      - Grundlagen: biosignale/basics.md
      - Physiologie: biosignale/physiologie.md
      - Klassifikation: biosignale/klassifikation.md
      - Messkette: biosignale/messkette.md
  - Elektrische Größen:
      - Einleitung: elektrische-groessen/eg-einleitung.md
      - Ladung, Strom, Spannung: elektrische-groessen/eg-groessen.md
      - Energie und Leistung: elektrische-groessen/eg-energie-und-leistung.md
      - Elektrische Leiter: elektrische-groessen/eg-leiter.md
  - Gleichstromtechnik:
      - Elektrische Widerstände: gleichstromtechnik/elektrische-widerstaende.md
      - Widerstandsnetze: gleichstromtechnik/widerstandsnetze.md
      - Gleichstromschaltungen: gleichstromtechnik/gleichstromschaltungen.md
      - Formale Lösungswege: gleichstromtechnik/formaler-loesungsweg.md
  - Elektrische Messtechnik:
      - Messverfahren: messverfahren.md
      - Überlagerungsprinzip: ueberlagerungsprinzip.md
  - Biomedizinische Sensortechnik: sensoren.md
  - Glossar: glossar.md
  - Quellen und Links: quellen.md
  - Über: about.md
  - 1. Test: test-1.md

theme:
  name: material
  favicon: images/favicon.ico
  logo: images/Skriptum_Logo.png
  language: de
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: Dunkelmodus

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list

extra_css:
  - stylesheets/logo.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
